apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mpis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-mpis@sha256:4d19991ffef76d37da32a4b4aedd9e0705b4fc371b2a02a32f6347e2dc57a2c7
        name: my-nodejs
        resources: {}
status: {}
